Repository green-ecolution/project-website, pull requests merged in 2024-06, with the labels that each got.

#20 ci: add workflow to test build
  .github/workflows/build-on-pr.yml
Labels: ci/cd

#22 Feature/add header
  public/assets/svg/logo/logo-large-color.svg
  src/main.tsx
  src/tsx/FakeProgress.tsx
  src/tsx/components/navigation/MainNavigation.tsx
  src/tsx/components/navigation/NavItem.tsx
  src/tsx/hooks/useOutsideClick.tsx
  src/tsx/icons/Arrow.tsx
  src/tsx/layout/Header.tsx
  tailwind.config.js
Labels: review

#25 feat: update readme
  README.md
Labels: review

#24 feat: add faq section
  index.html
  src/css/components/general.css
  src/css/frontend.css
  src/main.tsx
  src/tsx/App.tsx
  src/tsx/components/Accordion.tsx
  src/tsx/components/Faq.tsx
  tailwind.config.js
Labels: review

#26 feat: add stakeholder section as slider
  package.json
  public/assets/images/logo/hochschule-flensburg.png
  public/assets/images/logo/smarte-grenzregion.png
  public/assets/images/logo/tbz.png
  src/css/components/general.css
  src/css/components/splide.css
  src/css/frontend.css
  src/tsx/App.tsx
  src/tsx/components/Accordion.tsx
  src/tsx/components/StakeholderCard.tsx
  src/tsx/components/sections/Faq.tsx
  src/tsx/components/sections/Stakeholder.tsx
  src/tsx/helper/sliderTranslations.ts
  src/tsx/icons/Arrow.tsx
  src/types/splidejs__react-splide.d.ts
  tailwind.config.js
  yarn.lock
Labels: review

#31 feat: add favicons
  favicon.ico
  index.html
  public/assets/favicons/android-chrome-144x144.png
  public/assets/favicons/android-chrome-192x192.png
  public/assets/favicons/android-chrome-96x96.png
  public/assets/favicons/apple-touch-icon.png
  public/assets/favicons/favicon-16x16.png
  public/assets/favicons/favicon-32x32.png
  public/assets/favicons/favicon-48x48.png
  public/assets/favicons/favicon.svg
  public/assets/favicons/ms-icon-150x150.png
Labels: review

#30 feat: add introduction section
  public/assets/svg/general/location.svg
  public/assets/svg/general/sensor.svg
  public/assets/svg/general/statistics.svg
  public/assets/svg/general/tree.svg
  src/css/components/splide.css
  src/tsx/App.tsx
  src/tsx/components/IntroductionCard.tsx
  src/tsx/components/sections/Introduction.tsx
  src/tsx/components/sections/Stakeholder.tsx
  src/types/splidejs__react-splide.d.ts
Labels: review

#36 feat: add current process section
  .github/workflows/deploy_pull_request.yaml
  src/css/components/splide.css
  src/tsx/App.tsx
  src/tsx/components/cards/ProcessCard.tsx
  src/tsx/components/sections/Introduction.tsx
  src/tsx/components/sections/Process.tsx
  src/tsx/layout/Footer.tsx
  src/tsx/layout/Header.tsx
  src/types/splidejs__react-splide.d.ts
Labels: review, deploy

#41 feat: add project page
  .docker/Dockerfile.dev
  .docker/Dockerfile.prod
  .docker/Dockerfile.stage
  .docker/nginx.conf
  package.json
  public/assets/svg/background/general-light-dot.svg
  src/data/processSteps.ts
  src/main.tsx
  src/tsx/App.tsx
  src/tsx/FakeProgress.tsx
  src/tsx/components/Button.tsx
  src/tsx/components/Hero.tsx
  src/tsx/components/cards/IntroductionCard.tsx
  src/tsx/components/cards/ProcessCard.tsx
  src/tsx/components/cards/StakeholderCard.tsx
  src/tsx/components/navigation/MainNavigation.tsx
  src/tsx/components/process/StepCircle.tsx
  src/tsx/components/sections/Introduction.tsx
  src/tsx/components/sections/Process.tsx
  src/tsx/components/sections/Stakeholder.tsx
  src/tsx/layout/Header.tsx
  src/tsx/pages/HomePage.tsx
  src/tsx/pages/ProjectPage.tsx
  tailwind.config.js
  yarn.lock
Labels: review, deploy

#46 feat: add contact section
  src/tsx/components/Button.tsx
  src/tsx/components/sections/Contact.tsx
  src/tsx/layout/Footer.tsx
  src/tsx/pages/HomePage.tsx
  src/tsx/pages/ProjectPage.tsx
Labels: review

#43 feat: add dashboard preview section
  package.json
  src/json/dashboardAnimation.json
  src/tsx/components/sections/DashboardPreview.tsx
  src/tsx/components/sections/Hero.tsx
  src/tsx/pages/ProjectPage.tsx
  yarn.lock
Labels: review

#47 fix: same card height in process slider
  src/data/processSteps.ts
  src/tsx/components/sections/Process.tsx
Labels: bug, review

#45 feat: add advantages section
  public/assets/svg/general/eye.svg
  public/assets/svg/general/map.svg
  public/assets/svg/general/reduce.svg
  src/json/logoAnimation.json
  src/tsx/components/cards/AdvantageCard.tsx
  src/tsx/components/sections/Advantages.tsx
  src/tsx/layout/Header.tsx
  src/tsx/pages/ProjectPage.tsx
Labels: review

#58 ci: run cleanup action only when needed
  .editorconfig
  .github/workflows/cleanup_pull_request.yaml
Labels: review
